Be more verbose about curl errors

diff --git a/tools/multilayer_token b/tools/multilayer_token
--- a/tools/multilayer_token
+++ b/tools/multilayer_token
@@ -26,7 +26,11 @@ path="tiles/layergroup"
 #port=8083
 #path="database/cartodb_dev_user_1_db/layergroup"
 
-res=`curl -skH Content-Type:application/json --data-binary "@${cfg}" ${proto}://${user}.${domain}:${port}/${path}`
+cmd="curl -vskH Content-Type:application/json --data-binary @${cfg} ${proto}://${user}.${domain}:${port}/${path}"
+res=`${cmd}`
+if test $? -gt 0; then
+  echo "curl command failed: ${cmd}"
+fi
 
 if test x${verbose} = xyes; then
   echo "${res}"
